# Config file for server backend
# To run in dev mode, use `npm start`
# To run in production mode, use `npm run live`

split_threshold = 12 # server will attempt to split if player count greater or equal
merge_threshold = 5 # server will attempt to merge if player count lower or equal
reserve_ttl = 60 # expiry time of reservations (in seconds)

# To add a new server, create a new table with [server.servername]
[server.local]
dev = true
login = "serverlogin"
host = "127.0.0.1"
port = 5000
username = "SuperAdmin"
password = "SuperAdmin"
# or use `password_env = "ENV_VAR"` to store passwords in the environment
